# @package _global_
defaults:
- override /hydra/launcher: submitit_slurm

hydra:
  callbacks:
    log_job_return:
      _target_: hydra.experimental.callbacks.LogJobReturnCallback
  launcher:
    nodes: 1
    cpus_per_task: 2
    gpus_per_task: 1
    timeout_min: 2880
    constraint: "80gb|40gb"
    partition: gpu-2d
    qos:
    name: ${hydra.run.dir}/${hydra.job.override_dirname}
    max_num_timeout: 3
    stderr_to_stdout: true